version: '3.2'

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: backend
    container_name: backend
    ports:
    - "51773:51773"
    - "52773:52773"
    volumes:
    - ./backend:/app

  frontend:
    build:
      dockerfile: Dockerfile
      context: frontend
    container_name: frontend
    ports:
    - "4200:4200"
    volumes:
    - ./frontend:/app